#!/bin/bash
BASEDIR=$(pwd)

prepare() {
	sudo apt update
	sudo apt install -y git-core build-essential libssl-dev libncurses5-dev unzip gawk zlib1g-dev
	sudo apt install -y pkg-config u-boot-tools sudo python2.7 subversion wget dosfstools libconfuse-dev
	wget http://public.pengutronix.de/software/genimage/genimage-9.tar.xz
	tar xfvJ genimage-9.tar.xz
	cd $BASEDIR/genimage-9/
	./configure 
	make
	sudo make install
	cd $BASEDIR
}

clean() {
	rm -rf $BASEDIR/openwrt
}

clone_openwrt(){
	git clone https://github.com/openwrt/openwrt.git
	cp $BASEDIR/0001-changes-to-upstream-for-baltos.patch $BASEDIR/openwrt/
	cp $BASEDIR/feeds.conf $BASEDIR/openwrt/
	cp $BASEDIR/files $BASEDIR/openwrt/
	cd $BASEDIR/openwrt
	git apply 0001-changes-to-upstream-for-baltos.patch
	scripts/feeds update
	scripts/feeds install -a
	scripts/feeds install baltos
	cd $BASEDIR
}

build_image(){
	cp $BASEDIR/openwrt.config $BASEDIR/openwrt/.config
	cd $BASEDIR/openwrt
	make defconfig
	make
	cd $BASEDIR
}

create_sdcard(){
	cd $BASEDIR/openwrt/bin/baltos
	PATH=$PATH:/sbin/
	./mksdcard.sh
	cd $BASEDIR
}

case $1 in

prepare)
	prepare
	;;
get)
	clone_openwrt
	;;
make)
	build_image
	;;
sdcard)
	create_sdcard
	;;
all)
	prepare
	clone_openwrt
	build_image
	create_sdcard $2
	;;
clean)
	clean
	;;

esac

