#!/bin/bash
BASEDIR=$(pwd)

prepare() {
	echo Preparing build environment
	rm -f genimage-9.tar.xz
	wget http://public.pengutronix.de/software/genimage/genimage-9.tar.xz
	tar xfvJ genimage-9.tar.xz
	cd $BASEDIR/genimage-9/
	./configure 
	make
	cd $BASEDIR
}

clean() {
	echo Removing OpenWrt folder
	rm -rf $BASEDIR/openwrt
}

clone_openwrt(){
	echo Cloning OpenWrt repository
	git clone https://github.com/openwrt/openwrt.git
	cd $BASEDIR/openwrt
	git checkout v18.06.2
	cp $BASEDIR/feeds.conf $BASEDIR/openwrt/
	cp -r $BASEDIR/files $BASEDIR/openwrt/
	#git config user.email "contact@visionsystems.de"
	#git config user.name "Vision Systems GmbH"
	#git am $BASEDIR/patches/*
	scripts/feeds update
	scripts/feeds install -a
	scripts/feeds install baltos
	cd $BASEDIR
}

build_image(){
	echo Building OpenWrt
	cp $BASEDIR/openwrt.config $BASEDIR/openwrt/.config
	cd $BASEDIR/openwrt
	make defconfig
	make
	cd $BASEDIR
}

create_sdcard(){
	echo Creating SD card image
	cd $BASEDIR/openwrt/bin/targets/baltos/generic
	PATH=$PATH:$BASEDIR/genimage-9:/sbin
	./mksdcard.sh
	cd $BASEDIR
}

print_help(){
	echo build_openwrt usage:
	echo
	echo "./build_openwrt [prepare|get|make|sdcard|all|clean]"
	echo
	echo "  prepare  download and build genimage utility"
	echo "  get      clone OpenWrt repo and apply custom patches"
	echo "  make     build OpenWrt"
	echo "  sdcard   build OpenWrt SD card image"
	echo "  all      perform all above commands one after another"
	echo "  clean    remove openwrt folder"
}

case $1 in

prepare)
	prepare
	;;
get)
	clone_openwrt
	;;
make)
	build_image
	;;
sdcard)
	create_sdcard
	;;
all)
	prepare
	clone_openwrt
	build_image
	create_sdcard
	;;
clean)
	clean
	;;
*)
	print_help
	;;
esac

