#!/bin/bash
BASEDIR=$(pwd)

prepare() {
	echo Preparing build environment
	rm -f genimage-9.tar.xz
	wget http://public.pengutronix.de/software/genimage/genimage-9.tar.xz
	tar xfvJ genimage-9.tar.xz
	cd $BASEDIR/genimage-9/
	./configure 
	make
	cd $BASEDIR
}

clean() {
	echo Removing OpenWrt folder
	rm -rf $BASEDIR/openwrt
}

clone_openwrt(){
	echo Cloning OpenWrt repository
	git clone https://github.com/openwrt/openwrt.git
	cp $BASEDIR/feeds.conf $BASEDIR/openwrt/
	cp $BASEDIR/files $BASEDIR/openwrt/
	cd $BASEDIR/openwrt
	git am $BASEDIR/0001-changes-to-upstream-for-baltos.patch
	scripts/feeds update
	scripts/feeds install -a
	scripts/feeds install baltos
	cd $BASEDIR
}

build_image(){
	echo Building OpenWrt
	cp $BASEDIR/openwrt.config $BASEDIR/openwrt/.config
	cd $BASEDIR/openwrt
	make defconfig
	make
	cd $BASEDIR
}

create_sdcard(){
	echo Creating SD card image
	cd $BASEDIR/openwrt/bin/baltos
	PATH=$PATH:$BASEDIR/genimage-9
	./mksdcard.sh
	cd $BASEDIR
}

case $1 in

prepare)
	prepare
	;;
get)
	clone_openwrt
	;;
make)
	build_image
	;;
sdcard)
	create_sdcard
	;;
all)
	prepare
	clone_openwrt
	build_image
	create_sdcard $2
	;;
clean)
	clean
	;;

esac

