#!/bin/sh /etc/rc.common

START=21

start() {
	#set +e

        echo 'onrisc start'
	if [ ! -e /etc/config/onrisc ]; then
		/usr/bin/onriscinfo
	fi

	if [ ! -e /etc/config/netcom ]; then
		/usr/bin/vsconfs
	fi

	if [ -e /sys/bus/usb/devices/1-1.3\:*.3/uevent ] ; then
		source /sys/bus/usb/devices/1-1.3\:*.3/uevent
		if [ "$DRIVER" = "qcserial" ]; then
			DEVNAME=$(ls /sys/bus/usb/devices/1-1.3\:*.3/ | grep tty)
			ln -s /dev/$DEVNAME /dev/atcmd0
		fi
	fi

	if [ -e /sys/bus/usb/devices/1-1.3\:*.2/uevent ] ; then
		source /sys/bus/usb/devices/1-1.3\:*.2/uevent
		if [ "$DRIVER" = "option" ]; then
			DEVNAME=$(ls /sys/bus/usb/devices/1-1.3\:*.2/ | grep tty)
			ln -s /dev/$DEVNAME /dev/atcmd0
		fi
	fi

	/usr/bin/onrisctool -k 1

	/usr/bin/onrisctool -I

}

stop() {
        echo 'onrisc stop'
}
